version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: itemboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    networks:
      - itemboard-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:8000"
    networks:
      - itemboard-network
    depends_on:
      - database

networks:
  itemboard-network:
    driver: bridge
