version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: itemboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    networks:
      - mynetwork


  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/code
    ports:
      - "80:5000"
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:
    driver: bridge